//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMS.Models {
    using System;
    using System.Collections.Generic;

    public partial class Document {
        public Document() {
            this.ClientDocuments = new HashSet<ClientDocument>();
        }

        public long ID { get; set; }
        public long Number { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ConclusionDate { get; set; }
        public long OrganizationID { get; set; }
        public long CreatorID { get; set; }
        public Nullable<long> ModeratorID { get; set; }

        public virtual ICollection<ClientDocument> ClientDocuments { get; set; }
        public virtual UserData Creator { get; set; }
        public virtual UserData Moderator { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
