//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMS.Models {
    using System;
    using System.Collections.Generic;

    public partial class ModeratorDocument {
        public long ID { get; set; }
        public long ModeratorID { get; set; }
        public long DocumentID { get; set; }

        public virtual Document Document { get; set; }
        public virtual UserData Moderator { get; set; }
    }
}
