//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMS.Models {
    using System;
    using System.Collections.Generic;

    public partial class Organization {
        public Organization() {
            this.Documents = new HashSet<Document>();
            this.Users = new HashSet<UserData>();
        }

        public long ID { get; set; }
        public string Name { get; set; }
        public string LegalAdress { get; set; }
        public int Postcode { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<UserData> Users { get; set; }
    }
}
