//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMS.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Organization {
        public Organization() {
            this.Documents = new HashSet<Document>();
            this.Users = new HashSet<UserData>();
        }

        [Key]
        public long ID { get; set; }

        [Required]
        [Display(Name = "Название огранизации")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Юридический адрес")]
        public string LegalAdress { get; set; }

        [Required]
        [Display(Name = "Почтовый индекс")]
        public int Postcode { get; set; }

        [Required]
        [Display(Name = "Телефонный номер")]
        public string PhoneNumber { get; set; }

        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<UserData> Users { get; set; }
    }
}
